In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import tensorflow as tf

In [4]:
path="shakespeare.txt"

In [5]:
text=open(path,'r').read()

In [6]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [7]:
vocab=sorted(set(text))

In [8]:
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [9]:
len(vocab)

84

In [10]:
ind_to_char=np.array(vocab)

In [11]:
ind_to_char[0]

'\n'

In [12]:
char_to_ind={char:ind for ind,char in enumerate(vocab)}

In [13]:
char_to_ind['N']

39

In [14]:
encoded_text=np.array([char_to_ind[c] for c in text])

In [15]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [16]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [17]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [18]:
len('From fairest creatures we desire increase')

41

In [19]:
len('''
From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease

''')
#for every three lines there is a ryhme in last words of alternative lines..#so we can tkae the seq line as 120

133

In [20]:
seq_len=120

In [21]:
total_seq=len(text)//(seq_len+1)
#since index is from 0
total_seq

45005

In [22]:
char_dataset=tf.data.Dataset.from_tensor_slices(encoded_text)#gives tensorslices data set of tensor of the encoded text each one in seperate line
char_dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [23]:
#EXPLORING

In [24]:
for i in char_dataset.take(500):
    print(i)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(73, shape=(), dt

In [25]:
for i in char_dataset.take(500):
    print(ind_to_char[i.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


In [26]:
sequence=char_dataset.batch(seq_len+1,drop_remainder=True)

In [27]:
def convert(seq):
    input_data=seq[:-1]
    target_data=seq[1:]
    return input_data,target_data

In [28]:
summ=0
for i in sequence:
    summ=summ+1 #i is 120 long string in tensor slice(consiting of 120 tensor each one in seperate line) data type (3 lines)
   

In [29]:
summ#this much of 3 lines

45005

In [30]:
45380*120

5445600

In [31]:
len(text)#reminder=9

5445609

In [32]:
con=sequence.map(convert)

In [33]:
for inp,tar in con.take(1):
    print(inp.numpy())
    print("".join(ind_to_char[inp.numpy()]))
    print(tar.numpy())
    print("".join(ind_to_char[tar.numpy()]))#single blank space is extra here

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But
[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [34]:
buzzer_size=10000
dataset=con.shuffle(buzzer_size).batch(128,drop_remainder=True)#take a random of 10000 and take 128 from it
#without using shuufe we may end up taking data from continous para s
#picking from whole data set can cause memory leakage so we take random 10000 and take 128 from it

In [35]:
dataset#128 set of 120 tensor of ele containing encoded letters

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int32, tf.int32)>

In [36]:
voc_len=len(vocab)

In [37]:
embed_dim=64 #less than the voc_len as some of the vocab are not that important 
batch_size=128
rnn_neurons=1026

In [38]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy

In [39]:
SparseCategoricalCrossentropy()#if we check the params from_logit=False,we need it to be True
#as we deal with encoded values

In [40]:
def sparse_cat_crossentropy(y_true,pred):
    return SparseCategoricalCrossentropy(y_true,pred,from_logits=True)
#from_logits true as we pass encoded values
#we create a functn to change the from_logits as we wont call the funcnt below we paqss the name of the funtn only

In [41]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,GRU,Embedding

In [42]:
def create_model(voc_len,embed_dim,rnn_neurons,batch_size):
    model=Sequential()
    model.add(Embedding(voc_len,embed_dim,batch_input_shape=[batch_size,None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    model.add(Dense(voc_len)) 
    
    model.compile(loss=sparse_cat_crossentropy,optimizer='adam')  
    #sparse_cat_crossentropy passes y_true,pred
    return model          
    
    

In [43]:
sq=create_model(voc_len,embed_dim,rnn_neurons,batch_size)

In [44]:
sq.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (128, None, 64)           5376      
_________________________________________________________________
gru (GRU)                    (128, None, 1026)         3361176   
_________________________________________________________________
dense (Dense)                (128, None, 84)           86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [45]:
#use google colab as we dont have a gpu

In [46]:
from tensorflow.keras.models import load_model

In [72]:
for que,ans in dataset.take(1):
    pred=sq(que)#randomn pred as we didnt trai with anything yet..bunch of prob is the pred here
pred.shape

TensorShape([128, 120, 84])

In [146]:
single_index=tf.random.categorical(pred[0],num_samples=1)#single index as we dont need prob for each
#num_samples as we need only one ans
single_index

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[63],
       [41],
       [50],
       [78],
       [70],
       [74],
       [51],
       [76],
       [11],
       [22],
       [39],
       [73],
       [79],
       [28],
       [33],
       [46],
       [11],
       [56],
       [49],
       [19],
       [24],
       [19],
       [51],
       [ 9],
       [23],
       [ 1],
       [83],
       [10],
       [ 0],
       [63],
       [38],
       [82],
       [52],
       [15],
       [13],
       [41],
       [ 7],
       [ 4],
       [65],
       [ 8],
       [ 2],
       [73],
       [52],
       [67],
       [ 0],
       [82],
       [81],
       [79],
       [55],
       [ 6],
       [48],
       [ 4],
       [53],
       [55],
       [ 4],
       [18],
       [75],
       [77],
       [66],
       [57],
       [12],
       [36],
       [58],
       [51],
       [54],
       [17],
       [71],
       [78],
       [38],
       [67],
       [35],
       [74],
       [59],
   

In [147]:
single_index=tf.squeeze(single_index,-1)#to squeeze it into one axis 
single_index

<tf.Tensor: shape=(120,), dtype=int64, numpy=
array([63, 41, 50, 78, 70, 74, 51, 76, 11, 22, 39, 73, 79, 28, 33, 46, 11,
       56, 49, 19, 24, 19, 51,  9, 23,  1, 83, 10,  0, 63, 38, 82, 52, 15,
       13, 41,  7,  4, 65,  8,  2, 73, 52, 67,  0, 82, 81, 79, 55,  6, 48,
        4, 53, 55,  4, 18, 75, 77, 66, 57, 12, 36, 58, 51, 54, 17, 71, 78,
       38, 67, 35, 74, 59, 49, 72, 68, 37, 40, 59, 63, 68, 46, 53, 62, 77,
       28,  3,  8, 44,  0, 13,  7, 36, 58, 18, 23, 10, 31, 14, 16, 28, 36,
       30, 34, 52, 15, 26,  2, 79, 29, 36, 81, 67, 77, 61, 36, 64,  4, 64,
       58], dtype=int64)>

In [148]:
ind_to_char[single_index]#randomn pred as we didnt trai with anything yet..bunch of prob is the pred here

array(['h', 'P', 'Y', 'w', 'o', 's', 'Z', 'u', '0', ';', 'N', 'r', 'x',
       'C', 'H', 'U', '0', 'a', 'X', '8', '>', '8', 'Z', '-', '<', ' ',
       '}', '.', '\n', 'h', 'M', '|', '[', '4', '2', 'P', ')', '&', 'j',
       ',', '!', 'r', '[', 'l', '\n', '|', 'z', 'x', '`', '(', 'W', '&',
       ']', '`', '&', '7', 't', 'v', 'k', 'b', '1', 'K', 'c', 'Z', '_',
       '6', 'p', 'w', 'M', 'l', 'J', 's', 'd', 'X', 'q', 'm', 'L', 'O',
       'd', 'h', 'm', 'U', ']', 'g', 'v', 'C', '"', ',', 'S', '\n', '2',
       ')', 'K', 'c', '7', '<', '.', 'F', '3', '5', 'C', 'K', 'E', 'I',
       '[', '4', 'A', '!', 'x', 'D', 'K', 'z', 'l', 'v', 'f', 'K', 'i',
       '&', 'i', 'c'], dtype='<U1')

In [116]:
mod=create_model(voc_len,embed_dim,rnn_neurons,1)

In [117]:
mod.load_weights('shakespeare_gen.h5')

In [118]:
mod.build(tf.TensorShape([1,None]))

In [119]:
mod.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (1, None, 64)             5376      
_________________________________________________________________
gru_2 (GRU)                  (1, None, 1026)           3361176   
_________________________________________________________________
dense_2 (Dense)              (1, None, 84)             86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [127]:
def predict_text(model,string,gen_size,temp=1.0):
    input_val=[char_to_ind[i] for i in string]
    input_eval=tf.expand_dims(input_val,0)#to get the shape(put into a single array thats all)
    print(input_eval)
    text=[]
    model.reset_states()
    for i in range(gen_size):
        pred=model(input_eval)
        pred=tf.squeeze(pred,0)#take thevalues from seperate array and put into the main list
        pred=pred/temp#temperature is the learning rate  of a model
        pred=tf.random.categorical(pred,num_samples=1)[-1,0].numpy()#just formatiing
        input_eval=tf.expand_dims([pred],0)#to get the shape(put into a single array thats all)
        text.append(ind_to_char[pred])
    return(string+"".join(text))
print(predict_text(mod,"KING",500))    

tf.Tensor([[36 34 39 32]], shape=(1, 4), dtype=int32)
KINGESts, sure, E
    From ose of youth, not poor indeed I liv'd,
    Nor wife much wrong, when I should fear is silent.
  OTHELLO. O, I am in forbearer; be the place,
    Prizer. What! without muttons boister,
    A sinny spirit; let look sad round about
    From so the change of fortune.
  IAGO. By his beast-
  BISHOP OF EVALOUS. 'That man at learning, and 'a was not
    You may besee;
    Here we shall have them fish his action.
  GERTIMAN. You taste, let Antony is lae, against these coats.
  BAS


In [128]:
print(predict_text(mod,"KING",500))

tf.Tensor([[36 34 39 32]], shape=(1, 4), dtype=int32)
KINGETH 'Sey Sir Virona, I do feed myself
    From like head of his accidents; they can into her leg, a soldier-by
    uncleanlest France.
  POBTOL. I am no child; now, in good faith, it should be distable.
  THURIO. What, for a time, A friend?
  PAGE. Upon this surely stopp'd, I'll entertain myself:
    The first and white hair does, stand you with spoils
    At leisour for thee, antituith unto my word.
  LADY MACDUFF. Such matrons have you question,
    We'll back thy slanders both. What would the


In [130]:
s=np.array([[1,2,3]])

In [131]:
s

array([[1, 2, 3]])

In [132]:
s.shape

(1, 3)

1